### PR TITLE
Fixes #139  ignore white space character for search with dialpad numbers

### LINKED ISSUE #139: Character error on the keypad.
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11

### Affected device model

Xiaomi Note 8 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Open keypad.
Write some one. let "ı" or " " be in.

### Expected behavior

It find "ı" character and space character.

### Actual behavior

I type 8-6-6 to find "Tom" on the keypad and "Tom" comes out. But if there are too many "Tom" and I want to find "Tom Cruise"... When I typing 8-6-6-3, the space character can't identify and there are no results.

Likewise, the keypad also cannot find the "ı", which is a Turkish character. It find other Turkish characters. (s, ö, ü...) He can't find only "ı".

### Screenshots/Screen recordings

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Honk2**
#### What is it?
- [X] Bugfix
- [ ] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR
When searching contacts using the dialpad, 1 is handled as space character.
Also the white space symbol |_| is displayed below the 1 on the dialpad.

#### Fixes the following issue(s)

- Fixes #139 partly. Following the example given, Tom Cruise would by found by typing 8-6-6-1-3
- Does not fix the turkish character issue

#### Acknowledgement
- [X] I read the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aga-C** [comment]
It works, but I'm thinking it would be better to just ignore whitespaces while searching with numbers. Google Phone works this way, so I assume people are used to it. @naveensingh What do you think?

**Comment by naveensingh** [comment]
I think using 1 as a substitute for whitespace is quite arbitrary and no one would expect it. 

> I'm thinking it would be better to just ignore whitespaces while searching with numbers

Agreed. The search itself should be more 'intelligent' and display any relevant results.

**Comment by Honk2** [comment]
Got your point.
I changed the commit accordingly.

File: app/src/main/kotlin/org/fossify/phone/adapters/ContactsAdapter.kt [hunk 1]
```diff
@@ -368,7 +369,7 @@ class ContactsAdapter(
                     if (name.contains(textToHighlight, true)) {
                         name.highlightTextPart(textToHighlight, properPrimaryColor)
                     } else {
-                        name.highlightTextFromNumbers(textToHighlight, properPrimaryColor)
+                        name.highlightTextFromNumbers(textToHighlight.replace('1', ' '), properPrimaryColor)
```
Comment (naveensingh) [inline app/src/main/kotlin/org/fossify/phone/adapters/ContactsAdapter.kt:372]: I guess this is no longer need.

Comment (Honk2) [reply app/src/main/kotlin/org/fossify/phone/adapters/ContactsAdapter.kt]: Yes I just messed up the commits.

**Comment by naveensingh** [comment]
Works fine, thanks!

Ideally the app shouldn't highlight names when digits are entered in other tabs but that's an existing issue, not caused by this PR.
